export const countries = {
  'US': [
    ['AL', 'Alabama'],
    ['AK', 'Alaska'],
    ['AZ', 'Arizona'],
    ['AR', 'Arkansas'],
    ['CA', 'California'],
    ['CO', 'Colorado'],
    ['CT', 'Connecticut'],
    ['DE', 'Delaware'],
    ['DC', 'District of Columbia'],
    ['FL', 'Florida'],
    ['GA', 'Georgia'],
    ['HI', 'Hawaii'],
    ['ID', 'Idaho'],
    ['IL', 'Illinois'],
    ['IN', 'Indiana'],
    ['IA', 'Iowa'],
    ['KS', 'Kansas'],
    ['KY', 'Kentucky'],
    ['LA', 'Louisiana'],
    ['ME', 'Maine'],
    ['MD', 'Maryland'],
    ['MA', 'Massachusetts'],
    ['MI', 'Michigan'],
    ['MN', 'Minnesota'],
    ['MS', 'Mississippi'],
    ['MO', 'Missouri'],
    ['MT', 'Montana'],
    ['NE', 'Nebraska'],
    ['NV', 'Nevada'],
    ['NH', 'New Hampshire'],
    ['NJ', 'New Jersey'],
    ['NM', 'New Mexico'],
    ['NY', 'New York'],
    ['NC', 'North Carolina'],
    ['ND', 'North Dakota'],
    ['OH', 'Ohio'],
    ['OK', 'Oklahoma'],
    ['OR', 'Oregon'],
    ['PA', 'Pennsylvania'],
    ['RI', 'Rhode Island'],
    ['SC', 'South Carolina'],
    ['SD', 'South Dakota'],
    ['TN', 'Tennessee'],
    ['TX', 'Texas'],
    ['UT', 'Utah'],
    ['VT', 'Vermont'],
    ['VA', 'Virginia'],
    ['WA', 'Washington'],
    ['WV', 'West Virginia'],
    ['WI', 'Wisconsin'],
    ['WY', 'Wyoming'],
    ['AS', 'American Samoa'],
    ['FM', 'Federated States of Micronesia'],
    ['GU', 'Guam'],
    ['MP', 'Northern Mariana Islands'],
    ['PR', 'Puerto Rico'],
    ['MH', 'Republic of Marshall Islands'],
    ['VI', 'Virgin Islands of the U.S.'],
    ['AA', 'Armed Forces Americas'],
    ['AP', 'Armed Forces Pacific']
  ],
  'CA': [
    ['AB', 'Alberta'],
    ['BC', 'British Columbia'],
    ['MB', 'Manitoba'],
    ['NB', 'New Brunswick'],
    ['NL', 'Newfoundland and Labrador'],
    ['NT', 'Northwest Territories'],
    ['NS', 'Nova Scotia'],
    ['NU', 'Nunavut'],
    ['ON', 'Ontario'],
    ['PE', 'Prince Edward Island'],
    ['QC', 'Quebec'],
    ['SK', 'Saskatchewan'],
    ['YT', 'Yukon']
  ],
  'AU': [
    ['NSW', 'New South Wales'],
    ['VIC', 'Victoria'],
    ['QLD', 'Queensland'],
    ['TAS', 'Tasmania'],
    ['SA', 'South Australia'],
    ['WA', 'Western Australia'],
    ['NT', 'Northern Territory'],
    ['ACT', 'Australian Capital Territory']
  ],
  'NZ': [
    ['NZ-AUK', 'Auckland'],
    ['NZ-BOP', 'Bay of Plenty'],
    ['NZ-CAN', 'Canterbury'],
    ['NZ-GIS', 'Gisborne'],
    ['NZ-HKB', 'Hawke\'s Bay'],
    ['NZ-MBH', 'Marlborough'],
    ['NZ-MWT', 'Manawatu-Wanganui'],
    ['NZ-NSN', 'Nelson'],
    ['NZ-NTL', 'Northland'],
    ['NZ-OTA', 'Otago'],
    ['NZ-STL', 'Southland'],
    ['NZ-TAS', 'Tasman'],
    ['NZ-TKI', 'Taranaki'],
    ['NZ-WKO', 'Waikato'],
    ['NZ-WGN', 'Wellington'],
    ['NZ-WTC', 'West Coast'],
    ['NZ-CIT', 'Chatham Islands Territory']
  ],
  'IE': [
    ['IE-CW', 'Carlow'],
    ['IE-CN', 'Cavan'],
    ['IE-CE',	'Clare'],
    ['IE-CO',	'Cork'],
    ['IE-DL',	'Donegal'],
    ['IE-D', 'Dublin'],
    ['IE-G', 'Galway'],
    ['IE-KY',	'Kerry'],
    ['IE-KE',	'Kildare'],
    ['IE-KK',	'Kilkenny'],
    ['IE-LS',	'Laois'],
    ['IE-LM', 'Leitrim'],
    ['IE-LK', 'Limerick'],
    ['IE-LD',	'Longford'],
    ['IE-LH',	'Louth'],
    ['IE-MO',	'Mayo'],
    ['IE-MH', 'Meath'],
    ['IE-MN',	'Monaghan'],
    ['IE-OY',	'Offaly'],
    ['IE-RN', 'Roscommon'],
    ['IE-SO',	'Sligo'],
    ['IE-TA',	'Tipperary'],
    ['IE-WD', 'Waterford'],
    ['IE-WH', 'Westmeath'],
    ['IE-WX', 'Wexford'],
    ['IE-WW',	'Wicklow']
  ]
};
